name = "Nys-IP-PMM"
authors = ["Ya-Chi Chu", "Luiz-Rafael Santos", "Madeleine Udell"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FameSVD = "9ba2d756-9ce3-11e9-1a71-0ffcb019784d"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
LowRankApprox = "898213cb-b102-5a47-900c-97e73b919f73"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
OpenML = "8b6db2d4-7670-4922-a472-f9537c81ab66"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QPSReader = "10f199a5-22af-520b-b891-7ce84a7b1bd0"
RandomizedPreconditioners = "3e7891d3-c9d1-416a-9949-ebd96150e4f0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
DrWatson = "2.14.1"
julia = "1.9.1"
